sudo: required
services:
    - docker

before_install:
    - docker build -t msurmei/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true msurmei/react-test npm test

after_success:
    - docker build -t msurmei/multi-client ./client
    - docker build -t msurmei/multi-nginx ./nginx
    - docker build -t msurmei/multi-server ./server
    - docker build -t msurmei/multi-worker ./worker

    # docker login

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take images push to docker hub

    - docker push msurmei/multi-client
    - docker push msurmei/multi-nginx
    - docker push msurmei/multi-server
    - docker push msurmei/multi-worker

#deploy:
#    provider: elasticbeanstalk
#    region: us-east-2
#    app: multi-docker
#    env: MultiDocker-env
#    bucket_name: elasticbeanstalk-us-east-2-322042565622
#    bucket_path: docker-multi
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: $AWS_SECRET_KEY
